import os
import time
from urllib.parse import quote

# Path definitions 
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONSTITUTION_DIR = os.path.dirname(SCRIPT_DIR)
ROOT_DIR = os.path.dirname(CONSTITUTION_DIR)
# Also scan the parent folder (the master pack root)
PACK_ROOT = os.path.dirname(ROOT_DIR)

HELP_FILE = os.path.join(CONSTITUTION_DIR, "00.help.md")

IGNORE_DIRS = {'.git', '.claude', '__pycache__', 'node_modules', '.venv', 'venv', '.gemini', '.idea', '.vscode'}
IGNORE_FILES = {'.DS_Store', '00.help.md', 'auto_help.py'}

def generate_markdown():
    lines = [
        "# 🧭 00.help - Project Map & Master Directory\n\n",
        "> 🔄 **Self-Healing Document:** This file is automatically generated and updated by `auto_help.py`.\n> Any new folders or files added to the project will instantly appear below.\n\n",
        "## 🏗️ Project Architecture\n\n"
    ]
    
    for root, dirs, files in os.walk(PACK_ROOT):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS and not d.startswith('.')]
        dirs.sort()
        
        rel_path = os.path.relpath(root, PACK_ROOT)
        
        if rel_path == '.':
            lines.append("### 📁 Root\n")
            indent = ""
        else:
            level = rel_path.count(os.sep)
            indent = "  " * level
            folder_name = os.path.basename(root)
            lines.append(f"{indent}- **📂 {folder_name}/**\n")
            
        file_indent = indent + "  "
        valid_files = [f for f in files if f not in IGNORE_FILES and not f.startswith('.')]
        valid_files.sort()
        
        for f in valid_files:
            abs_path = os.path.join(root, f)
            rel_file = os.path.relpath(abs_path, PACK_ROOT)
            rel_file_fwd = rel_file.replace('\\', '/')
            rel_uri = quote(rel_file_fwd)
            lines.append(f"{file_indent}- 📄 [{f}](./{rel_uri})\n")
            
    return "".join(lines)

def update_help_file():
    content = generate_markdown()
    
    try:
        if os.path.exists(HELP_FILE):
            with open(HELP_FILE, 'r', encoding='utf-8') as f:
                if f.read() == content:
                    return False
    except Exception:
        pass
        
    with open(HELP_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    return True

if __name__ == "__main__":
    print(f"🚀 Starting Auto-Help Watcher in: {ROOT_DIR}")
    print("👀 Watching for file changes... Press Ctrl+C to stop.")
    
    if update_help_file():
        print("✅ Created initial 00.help.md")
    else:
        print("✅ 00.help.md is already up to date")
        
    try:
        while True:
            time.sleep(2)
            if update_help_file():
                print("🔄 00.help.md updated!")
    except KeyboardInterrupt:
        print("\n🛑 Watcher stopped.")
